[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "pls-cli"
version = "0.1.1"
description = "Automation tool for organizing directories in Linux"
readme = "README.MD"
requires-python = ">=3.10"
dependencies = [
    "watchdog>=3.0.0"
]

[project.scripts]
pls = "main:main"
